GET http://localhost:3000/subscribers

###


GET http://localhost:3000/subscribers/685a071bb5a3fc7699aff85d


###
POST http://localhost:3000/subscribers
Content-Type: application/json

{
  "name": "Amazing Person",
  "subscribedToChannel":"Web Dev Simplified"
}


###
DELETE http://localhost:3000/subscribers/685a071bb5a3fc7699aff85d

###
PATCH http://localhost:3000/subscribers/685a071bb5a3fc7699aff85d
Content-Type: application/json

{
  "name": "New Name"
}